config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # include Geocoder::Model::Mongoid
geocoded_by :ip_address,
  :latitude => :lat, :longitude => :lon
after_validation :geocode



# geocoded_by :postal_code,
#   :latitude => :lat, :longitude => :lon
# after_validation :geocode

# http://stackoverflow.com/questions/6770784/how-to-create-popup-window-to-create-new-record-in-rails-3


  def user_ip
  	request.location
  end

end

 	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@users = User.all
  	@result = request.location
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  	  # @result = request.location
  	  redirect_to root_path
  	else 
  	  render :new
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name)
  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geolocation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>

<%= link_to 'new', new_user_path %><br>

Your IP address is: <%= @result.ip %><br>
Your lat is: <%= @result.latitude %><br>
Your lon is: <%= @result.longitude %><br>
Your coordinates are: <%= @result.coordinates %><br>
Your address is: <%= @result.address %><br>
<%= @result.postal_code %><br>
<br>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@result.latitude}%2C#{@result.longitude}" %><br>


These are all methods for gem: <br>
<br>
result.latitude - float <br>
result.longitude - float <br>
result.coordinates - array of the above two <br>
result.address - string <br>
result.city - string <br>
result.state - string <br>
result.state_code - string <br>
result.postal_code - string <br>
result.country - string <br>
result.country_code - string <br>

app/views/users/new.html.erb
<h1> New User </h1>
<%= form_for @user do |f| %>
  <%= f.label :name %>: 
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>